[project]
name = "my-sales-mvp"
authors = []
description = "A sales tracking smart contract with tiered commission calculation"
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.sales-contract]
path = "contracts/sales-contract.clar"
depends_on = []

[contracts.commission-manager]
path = "contracts/commission-manager.clar"
depends_on = ["sales-contract"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
